### REGISTER USER BARU
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "name": "user4",
  "email": "user4@gmail.com",
  "password": "user4"
}

### LOGIN USER
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "email": "user4@gmail.com",
  "password": "user4"
}